position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
   - shoulder_pan_joint
   - shoulder_lift_joint
   - elbow_joint
   - wrist_1_joint
   - wrist_2_joint
   - wrist_3_joint
  constraints:
    goal_time: 0.5
    elbow_joint:
      goal: 0.05
    shoulder_lift_joint:
      goal: 0.05
    shoulder_pan_joint:
      goal: 0.05
    wrist_1_joint:
      goal: 0.05
    wrist_2_joint:
      goal: 0.05
    wrist_3_joint:
      goal: 0.05
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30  # [Hz]
